apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: ose-secret-configmap-eap
  name: ose-secret-configmap-eap
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: ose-secret-configmap-eap
    deploymentconfig: ose-secret-configmap-eap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
